import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Navbar />
				<main className="min-h-[calc(100vh-117px)] sm:min-h-[calc(100vh-76.8px)] px-8 py-24">
					{children}
				</main>
				<Footer />
			</body>
		</html>
	);
}
